data:
  path: "/home/wgzhong/pywork/datasets/pa100k"
  mode: "resize"

model:
  model_name: "mobilenetv3_small"
  img_size_h: 256
  img_size_w: 128
train:
  optimizer_name: adam
  loss: "binary_focal"
  bfl:
    gamma: 2.0
    alpha: 0.25
    epsilon: 1.e-8
  sfl:
    gamma: 2.0
    alpha: 0.25
    epsilon: 1.e-8
  lr: 0.0001
  epochs: 500
  batch_size: 128
  num_classes: 4
