data:
  path: "/home/vastai/zwg/pa100k"
  mode: "resize"

model:
  model_name: "mobilenetv3_small"
  img_size_h: 224
  img_size_w: 112
train:
  optimizer_name: adam
  age_loss: "softmax_focal"
  gender_loss: "binary_focal"
  bfl:
    gamma: 2.0
    alpha: 0.25
    epsilon: 1.e-8
  sfl:
    gamma: 2.0
    alpha: 0.25
    epsilon: 1.e-8
  lr: 0.0001
  epochs: 500
  batch_size: 128
  age_num: 3
  gender_num: 1
